---
# tasks file for user-standard

- name: Set authorized SSH key for user {{ standard_user }}
  authorized_key:
    user: "{{ standard_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - files/*.pub
