---
# tasks file for user-standard

- block: # Admin user
  - name: Ensure that the {{ standard_user }} account exists
    user:
      name: "{{ standard_user }}"
      password: "{{ standard_pass | string | password_hash('sha512', 'standardsalt') }}"
      state: present
      update_password: on_create
      shell: /bin/bash
      groups: sudo
      append: yes
    when: not set_pass
  - name: Ensure that the {{ standard_user }} account exists and reset the password
    user:
      name: "{{ standard_user }}"
      password: "{{ standard_pass | string | password_hash('sha512', 'standardsalt') }}"
      state: present
      update_password: always
      shell: /bin/bash
      groups: sudo
      append: yes
    when: set_pass 
  when: admin_user

- block: # Non-admin user
  - name: Ensure that the {{ standard_user }} account exists
    user:
      name: "{{ standard_user }}"
      password: "{{ standard_pass | string | password_hash('sha512', 'standardsalt') }}"
      state: present
      update_password: on_create
      shell: /bin/bash
    when: not set_pass
  - name: Ensure that the {{ standard_user }} account exists and reset the password
    user:
      name: "{{ standard_user }}"
      password: "{{ standard_pass | string | password_hash('sha512', 'standardsalt') }}"
      state: present
      update_password: always
      shell: /bin/bash
    when: set_pass 
  when: not admin_user

- name: Set authorized SSH key for user {{ standard_user }}
  authorized_key:
    user: "{{ standard_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - files/*.pub

- name: Template out the .bashrc file for user {{ standard_user }}
  template:
    src: bashrc.j2
    dest: "/home/{{ standard_user }}/.bashrc"
    owner: "{{ standard_user }}"
    group: "{{ standard_user }}"
    mode: '644'

- name: Copy over the .bash_profile file for user {{ standard_user }}
  copy:
    src: bash_profile
    dest: "/home/{{ standard_user }}/.bash_profile"
    owner: "{{ standard_user }}"
    group: "domain users"
    mode: '644'
    force: yes